import { Document, Page, Text, View, StyleSheet, Link } from '@react-pdf/renderer'
import type { Report, TopicResources } from '@/types/report'

interface QuizReportPDFProps {
  report: Report
  questions: Array<{
    id: string
    question: string
    type: 'multiple-choice' | 'descriptive'
    correct_answer: string
    user_answer: string | null
    is_correct: boolean | null
  }>
}

const VIOLET = '#7c3aed'
const DARK = '#1e1b4b'
const GREY = '#64748b'
const LIGHT_BG = '#f8fafc'
const BORDER = '#e2e8f0'
const SUCCESS = '#059669'
const ERROR = '#dc2626'
const WARNING = '#d97706'

const s = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: DARK,
    paddingHorizontal: 48,
    paddingVertical: 48,
  },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: VIOLET, marginBottom: 4 },
  subtitle: { fontSize: 11, color: GREY, marginBottom: 20 },
  section: { marginBottom: 18 },
  h2: {
    fontSize: 13,
    fontFamily: 'Helvetica-Bold',
    color: DARK,
    marginBottom: 6,
    paddingBottom: 3,
    borderBottom: `1px solid ${BORDER}`,
  },
  h3: { fontSize: 11, fontFamily: 'Helvetica-Bold', color: DARK, marginBottom: 4 },
  prose: { fontSize: 10, color: GREY, lineHeight: 1.6, marginBottom: 6 },
  scoreBadge: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: VIOLET },
  metaRow: { flexDirection: 'row', gap: 12, marginBottom: 14 },
  metaChip: {
    backgroundColor: LIGHT_BG,
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  metaChipText: { fontSize: 9, color: GREY },
  table: { width: '100%', borderRadius: 4, overflow: 'hidden', marginTop: 6 },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: LIGHT_BG,
    borderBottom: `1px solid ${BORDER}`,
    paddingVertical: 5,
    paddingHorizontal: 6,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: `1px solid ${BORDER}`,
    paddingVertical: 5,
    paddingHorizontal: 6,
  },
  col1: { width: '40%' },
  col2: { width: '12%' },
  col3: { width: '22%' },
  col4: { width: '22%' },
  col5: { width: '4%', textAlign: 'center' },
  headerText: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: GREY },
  cellText: { fontSize: 8, color: GREY, lineHeight: 1.4 },
  divider: { borderBottom: `1px solid ${BORDER}`, marginVertical: 14 },
  bullet: { flexDirection: 'row', marginBottom: 3 },
  bulletDot: { width: 12, fontSize: 10, color: WARNING },
  tierLabel: { fontSize: 9, fontFamily: 'Helvetica-Bold', marginBottom: 3, marginTop: 4 },
  resourceRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 2, gap: 4 },
  resourceTitle: { fontSize: 9, color: DARK, flex: 1 },
  resourceType: { fontSize: 8, color: GREY, width: 60 },
})

function ScoreColor(score: number): string {
  if (score >= 80) return SUCCESS
  if (score >= 60) return WARNING
  return ERROR
}

function TierSection({ items, label }: { items: TopicResources['free']; label: string }) {
  if (items.length === 0) return null
  return (
    <View>
      <Text
        style={[
          s.tierLabel,
          { color: label === 'Free' ? SUCCESS : label === 'Freemium' ? WARNING : VIOLET },
        ]}
      >
        {label}
      </Text>
      {items.map((item) => (
        <View key={item.url} style={s.resourceRow}>
          <Text style={s.resourceTitle}>{item.title}</Text>
          <Text style={s.resourceType}>{item.type}</Text>
          <Link
            src={item.url}
            style={{ fontSize: 8, color: VIOLET, textDecoration: 'underline', width: 60 }}
          >
            Link
          </Link>
        </View>
      ))}
    </View>
  )
}

export function QuizReportPDF({ report, questions }: QuizReportPDFProps) {
  const score = report.score_percentage
  const dateStr = new Date(report.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  const totalQ = questions.length
  const correct = questions.filter((q) => q.is_correct).length
  const struggling = report.struggling_topics ?? []
  const resumeParas = report.learning_resume?.split(/\n\n+/) ?? []

  return (
    <Document>
      <Page size="A4" style={s.page}>
        {/* Title */}
        <Text style={s.title}>{report.subject_area} — Quiz Report</Text>
        <Text style={s.subtitle}>Generated by OctoLearn</Text>

        {/* Meta */}
        <View style={s.metaRow}>
          <View style={s.metaChip}>
            <Text style={s.metaChipText}>📅 {dateStr}</Text>
          </View>
          <View style={s.metaChip}>
            <Text style={[s.metaChipText, { color: ScoreColor(score) }]}>
              Score: {correct}/{totalQ} — {score}%
            </Text>
          </View>
          <View style={s.metaChip}>
            <Text style={s.metaChipText}>Topics: {report.topics_covered.join(', ')}</Text>
          </View>
        </View>

        {/* Summary */}
        <View style={s.section}>
          <Text style={s.h2}>Quiz Summary</Text>
          <Text style={s.prose}>{report.summary}</Text>
        </View>

        {/* Areas to review */}
        {struggling.length > 0 && (
          <View style={s.section}>
            <Text style={s.h2}>Areas to Review</Text>
            {struggling.map((t) => (
              <View key={t} style={s.bullet}>
                <Text style={s.bulletDot}>• </Text>
                <Text style={[s.prose, { marginBottom: 0 }]}>{t}</Text>
              </View>
            ))}
          </View>
        )}

        {/* Question breakdown */}
        <View style={s.section}>
          <Text style={s.h2}>Question Breakdown</Text>
          <View style={s.table}>
            <View style={s.tableHeader}>
              <Text style={[s.headerText, s.col1]}>Question</Text>
              <Text style={[s.headerText, s.col2]}>Type</Text>
              <Text style={[s.headerText, s.col3]}>Your answer</Text>
              <Text style={[s.headerText, s.col4]}>Correct answer</Text>
              <Text style={[s.headerText, s.col5]}>✓</Text>
            </View>
            {questions.map((q) => (
              <View key={q.id} style={s.tableRow}>
                <Text style={[s.cellText, s.col1]}>{q.question}</Text>
                <Text style={[s.cellText, s.col2]}>
                  {q.type === 'multiple-choice' ? 'MC' : 'Desc'}
                </Text>
                <Text style={[s.cellText, s.col3]}>{q.user_answer ?? '—'}</Text>
                <Text style={[s.cellText, s.col4]}>{q.correct_answer}</Text>
                <Text style={[s.cellText, s.col5, { color: q.is_correct ? SUCCESS : ERROR }]}>
                  {q.is_correct ? '✓' : '✗'}
                </Text>
              </View>
            ))}
          </View>
        </View>

        <View style={s.divider} />

        {/* Learning resume */}
        {report.learning_resume && (
          <View style={s.section}>
            <Text style={s.h2}>Learning Resume</Text>
            {resumeParas.map((para, i) => (
              <Text key={i} style={s.prose}>
                {para}
              </Text>
            ))}
          </View>
        )}

        {/* References */}
        {report.resources && report.resources.length > 0 && (
          <View style={s.section}>
            <Text style={s.h2}>References & Resources</Text>
            {report.resources.map((tr) => (
              <View key={tr.topic} style={{ marginBottom: 10 }}>
                <Text style={s.h3}>{tr.topic}</Text>
                <TierSection items={tr.free} label="Free" />
                <TierSection items={tr.freemium} label="Freemium" />
                <TierSection items={tr.paid} label="Paid" />
              </View>
            ))}
          </View>
        )}
      </Page>
    </Document>
  )
}
